### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by caoziyang1997** [YCaigogogo/CVPR24-CODER#1]
请问你这个虚拟环境要求是多少，以及所要的依赖包

**Comment by YCaigogogo** [comment]
感谢关注，torch / torchvision / openai的版本列在了README.md里，numpy版本为1.23.3。

**Comment by caoziyang1997** [comment]
可以提供一下imagenet数据集下载的链接吗，我从kaggle上下载的数据集，运行起来报错。
